### Create Company
POST http://localhost:3000/company
Content-Type: application/json

{
  "name": "Apple Inc222",
  "legalNumber": "xx",
  "incorporationCountry": "USA",
  "website": "https://apple.com"
}

###

### Get All Companies
GET http://localhost:3000/company

###

### Update Company
PUT http://localhost:3000/company/cmqfj8qou000g137tnkn76vbv
Content-Type: application/json

{
  "name": "Apple Inc22 Updated",
  "incorporationCountry": "United States",
  "website": "https://apple.com"
}

###

### Delete Company
DELETE http://localhost:3000/company/cmqf7qd0m000e8v0lphtyddke


#################################################
### PRODUCT API
#################################################

### Create Product
POST http://localhost:3000/product
Content-Type: application/json

{
  "name": "iPhone 15",
  "category": "Electronics",
  "amount": 999,
  "amountUnit": "USD",
  "companyId": "cmqf7rvpe0003137twqho76x1"
}

###

### Get All Products
GET http://localhost:3000/product

###

### Update Product
PUT http://localhost:3000/product/cmqf7tj21000b137tzc4v5k3i
Content-Type: application/json

{
  "name": "iPhone 15 Pro",
  "category": "Electronics",
  "amount": 1299,
  "amountUnit": "USD"
}

###

### Delete Product
DELETE http://localhost:3000/product/cmqf7tj21000b137tzc4v5k3i 

